// Generates the art attribution the app shows in ⚙️ → เครดิตงานศิลป์.
//
//   node apps/web/scripts/build-credits.mjs
//
// The avatar sprites come from the Universal LPC Spritesheet project, whose
// sheet definitions carry per-part authors, licences and source URLs. Several of
// those licences (CC-BY, CC-BY-SA, OGA-BY, GPL) require attribution wherever the
// work is published, so this reads the definitions in assets/lpc-src, keeps only
// the parts actually shipped in public/lpc/spritesheets, and writes:
//
//   src/artCredits.ts          summary shown in the dialog
//   public/lpc/CREDITS.txt     every part, with notes and URLs, linked from it
//
// Re-run it after adding or removing spritesheets.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// fileURLToPath, not url.pathname: this repo's path contains spaces, which stay
// percent-encoded in a file URL and turn into a directory that does not exist
const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.resolve(here, "..");
const repo = path.resolve(web, "../..");

const walk = (d) =>
  fs.existsSync(d)
    ? fs.readdirSync(d, { withFileTypes: true })
        .flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]))
    : [];

// ---- which avatar parts do we actually ship? ----
const sheetRoot = path.join(web, "public/lpc/spritesheets");
const shipped = new Set(
  walk(sheetRoot).filter((f) => f.endsWith(".png"))
    .map((f) => path.relative(sheetRoot, path.dirname(f)).split(path.sep).join("/")),
);

// ---- pull the credits for those parts out of the source definitions ----
const defs = walk(path.join(repo, "assets/lpc-src/sheet_definitions")).filter((f) => f.endsWith(".json"));
const used = [];
for (const f of defs) {
  let j;
  try { j = JSON.parse(fs.readFileSync(f, "utf8")); } catch { continue; }
  for (const c of j.credits ?? []) {
    if (!c.file) continue;
    if (![...shipped].some((s) => s === c.file || s.startsWith(`${c.file}/`))) continue;
    used.push({ part: j.name || j.type_name || path.basename(f, ".json"), ...c });
  }
}

const uniq = (xs) => [...new Set(xs.filter(Boolean))].sort((a, b) => a.localeCompare(b, "en"));
const authors = uniq(used.flatMap((c) => c.authors ?? []));
// OGA-BY-3.0 and OGA-BY 3.0 are the same licence spelled two ways in the source
const licenses = uniq(used.flatMap((c) => (c.licenses ?? []).map((l) => l.replace("OGA-BY-3.0", "OGA-BY 3.0"))));
const urls = uniq(used.flatMap((c) => c.urls ?? []));

if (!used.length) {
  console.error("no matching credits found — did public/lpc/spritesheets move?");
  process.exit(1);
}

// ---- the full list, served as a plain file and linked from the dialog ----
const txt = [
  "NexSpace — avatar sprite credits",
  "",
  "The avatar sprites are from the Universal LPC Spritesheet project. Every part",
  "shipped with this app is listed below with its authors, licences and sources.",
  `Generated from assets/lpc-src/sheet_definitions — ${used.length} entries, ${authors.length} artists.`,
  "",
  "=".repeat(78),
  "",
  ...used.flatMap((c) => [
    `PART      ${c.part}`,
    `FILE      ${c.file}`,
    c.notes ? `NOTES     ${c.notes}` : null,
    `AUTHORS   ${(c.authors ?? []).join(", ")}`,
    `LICENCES  ${(c.licenses ?? []).join(", ")}`,
    ...(c.urls ?? []).map((u) => `SOURCE    ${u}`),
    "",
  ].filter((l) => l !== null)),
].join("\n");
fs.writeFileSync(path.join(web, "public/lpc/CREDITS.txt"), txt);

// ---- the summary module ----
const ts = `// GENERATED by scripts/build-credits.mjs — do not edit by hand.
// Re-run that script after changing which spritesheets ship.
export interface CreditGroup {
  title: string;
  what: string;
  authors: string[];
  licenses: string[];
  urls: { label: string; href: string }[];
  /** link to the exhaustive per-part list, when a summary is not the whole story */
  fullList?: string;
}

/** artists whose work is in the avatar sprites this app ships */
export const AVATAR_AUTHOR_COUNT = ${authors.length};

export const ART_CREDITS: CreditGroup[] = [
  {
    title: 'ธีม "ออฟฟิศคลาสสิก" — เฟอร์นิเจอร์และของตกแต่ง',
    what: "โต๊ะ ตู้ แล็ปท็อป แก้วกาแฟ เครื่องถ่ายเอกสาร ตู้กดน้ำ ทีวี และภาพติดผนัง (LPC \\"The Office\\")",
    authors: ["Eliza Wyatt", "Lanea Zimmerman (Sharm)"],
    licenses: ["OGA-BY 3.0"],
    urls: [
      { label: "ต้นฉบับ (GitHub)", href: "https://github.com/ElizaWy/LPC" },
      { label: "ข้อความสัญญาอนุญาต OGA-BY 3.0", href: "https://static.opengameart.org/OGA-BY-3.0.txt" },
    ],
  },
  {
    title: 'ธีม "ออฟฟิศคลาสสิก" — โต๊ะทำงาน เก้าอี้ และคอมพิวเตอร์',
    what: "ตัดจาก CoolSchool tileset (48px วางขนาดจริง)",
    authors: ["NettySvit"],
    licenses: ["CC0 1.0"],
    urls: [{ label: "CC0 1.0", href: "https://creativecommons.org/publicdomain/zero/1.0/" }],
  },
  {
    title: "ตัวละครและชุดแต่งตัว (ทุกธีม)",
    what: "ชิ้นส่วนอวาตาร์ ${used.length} รายการจากโครงการ Universal LPC Spritesheet",
    authors: ${JSON.stringify(authors)},
    licenses: ${JSON.stringify(licenses)},
    urls: [
      { label: "Universal LPC Spritesheet", href: "https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator" },
      { label: "Liberated Pixel Cup", href: "https://lpc.opengameart.org/" },
    ],
    fullList: "/lpc/CREDITS.txt",
  },
  {
    title: "แผนผัง พื้น กำแพง และของตกแต่งอื่น ๆ",
    what: "สร้างขึ้นสำหรับ NexSpace ด้วย PixelLab",
    authors: ["NexSpace"],
    licenses: ["CC0 1.0"],
    urls: [],
  },
];
`;
fs.writeFileSync(path.join(web, "src/artCredits.ts"), ts);

console.log(`credits: ${used.length} parts, ${authors.length} artists, ${licenses.length} licences`);
console.log("wrote src/artCredits.ts and public/lpc/CREDITS.txt");
