// GENERATED by scripts/build-credits.mjs — do not edit by hand.
// Re-run that script after changing which spritesheets ship.
export interface CreditGroup {
  title: string;
  what: string;
  authors: string[];
  licenses: string[];
  urls: { label: string; href: string }[];
  /** link to the exhaustive per-part list, when a summary is not the whole story */
  fullList?: string;
}

/** artists whose work is in the avatar sprites this app ships */
export const AVATAR_AUTHOR_COUNT = 71;

export const ART_CREDITS: CreditGroup[] = [
  {
    title: 'ธีม "ออฟฟิศคลาสสิก" — เฟอร์นิเจอร์และของตกแต่ง',
    what: "โต๊ะ ตู้ แล็ปท็อป แก้วกาแฟ เครื่องถ่ายเอกสาร ตู้กดน้ำ ทีวี และภาพติดผนัง (LPC \"The Office\")",
    authors: ["Eliza Wyatt", "Lanea Zimmerman (Sharm)"],
    licenses: ["OGA-BY 3.0"],
    urls: [
      { label: "ต้นฉบับ (GitHub)", href: "https://github.com/ElizaWy/LPC" },
      { label: "ข้อความสัญญาอนุญาต OGA-BY 3.0", href: "https://static.opengameart.org/OGA-BY-3.0.txt" },
    ],
  },
  {
    title: 'ธีม "ออฟฟิศคลาสสิก" — โต๊ะทำงาน เก้าอี้ และคอมพิวเตอร์',
    what: "ตัดจาก CoolSchool tileset (48px วางขนาดจริง)",
    authors: ["NettySvit"],
    licenses: ["CC0 1.0"],
    urls: [{ label: "CC0 1.0", href: "https://creativecommons.org/publicdomain/zero/1.0/" }],
  },
  {
    title: "ตัวละครและชุดแต่งตัว (ทุกธีม)",
    what: "ชิ้นส่วนอวาตาร์ 749 รายการจากโครงการ Universal LPC Spritesheet",
    authors: ["??","7Soul","Ahmad3366","AntumDeluge","Barbara Riviera","Benjamin K. Smith (BenCreating)","bluecarrot16","Bluecarrot16","Carlo Enrico Victoria (Nemisys)","Charles Sanchez (CharlesGabriel)","Cobra Hubbard (BlueVortexGames)","dalonedrau","Daniel Eddeland (daneeklu)","DarkwallLKE","DCSS authors","Dr. Jamgo","drjamgo@hotmail.com","Durrani","Eliza Wyatt","Eliza Wyatt (ElizaWy)","ElizaWy","ElizaWy; walk and down by JaidynReiman","Emilio J. Sanchez-Sierra","Evert","Fabzy","gr3yh47","Inboxninja","JaidynReiman","Joe White","Johannes Sjölund (wulax)","Joshua Taylor","kcilds/Rocetti/Eredah","kheftel","kirts","laetissima","Lanea Zimmerman (Sharm)","LordNeo","Luke Mehl","macmanmatty","Makrohn","Mandi Paugh","Manuel Riecke (MrBeast)","Marcel van de Steeg (MadMarcel)","Matthew Krohn (makrohn)","Matthew Krohn (Makrohn)","Michael Whitlock (bigbeargames)","MuffinElZangano","Napsio (Vitruvian Studio)","Nila122","Nyom","Page","Pierre Vigier (pvigier)","Pierre Vigier and DCSS artists (see https://github.com/crawl/tiles/blob/master/ARTISTS.md)","PlatForge project","Radomir Dopieralski","Sander Frenken (castelonia)","Shaun Williams","Skorpio","Stafford McIntyre","Stephen Challener (Redshrike)","Thane Brimhall (pennomi)","The Foreman","thecilekli","TheraHedwig","Tracy","tskaufma","Tuomo Untinen (reemax)","William.Thompsonj","William.Thomsponj","Yamilian","Zi Ye"],
    licenses: ["CC-BY","CC-BY 3.0","CC-BY 3.0+","CC-BY 4.0","CC-BY 4.0+","CC-BY-SA 3.0","CC-BY-SA 3.0+","CC-BY-SA 4.0","CC0","GPL 2.0","GPL 2.0+","GPL 3.0","GPL 3.0+","OGA-BY 3.0","OGA-BY 3.0+","OGA-BY 4.0","OGA-SA 3.0"],
    urls: [
      { label: "Universal LPC Spritesheet", href: "https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator" },
      { label: "Liberated Pixel Cup", href: "https://lpc.opengameart.org/" },
    ],
    fullList: "/lpc/CREDITS.txt",
  },
  {
    title: "แผนผัง พื้น กำแพง และของตกแต่งอื่น ๆ",
    what: "สร้างขึ้นสำหรับ NexSpace ด้วย PixelLab",
    authors: ["NexSpace"],
    licenses: ["CC0 1.0"],
    urls: [],
  },
];
