// GENERATED by scripts/asset-catalogue.mjs — do not edit by hand.
//
// Every prop the map editor may place, read off apps/web/public/assets. Those
// files live in public/, which Vite copies rather than compiles, so nothing in
// the bundle would otherwise know they exist.
//
// Chairs are listed once each, facing south: the game rotates a placed chair,
// and offering all eight directions would be 128 palette entries for 16 chairs.
//
// Regenerate with:  node scripts/asset-catalogue.mjs

export interface PropGroup {
  /** the folder on disk, and the fallback folder for its bare keys */
  dir: string;
  label: string;
  keys: string[];
}

/** 114 props across 4 groups */
export const CATALOGUE: PropGroup[] = [
  {
    "dir": "furniture",
    "label": "เฟอร์นิเจอร์",
    "keys": [
      "arcade",
      "armchair",
      "bean-bag",
      "bed",
      "beverage-cooler",
      "bookshelf",
      "chair-1-south",
      "chair-10-south",
      "chair-11-south",
      "chair-12-south",
      "chair-13-south",
      "chair-14-south",
      "chair-15-south",
      "chair-16-south",
      "chair-2-south",
      "chair-3-south",
      "chair-4-south",
      "chair-5-south",
      "chair-6-south",
      "chair-7-south",
      "chair-8-south",
      "chair-9-south",
      "coffee-machine",
      "conference-table",
      "counter",
      "desk",
      "desk-monitor",
      "dining-set",
      "floor-lamp",
      "fridge",
      "gaming-tv",
      "kitchen-counter",
      "lounge-coffee-table",
      "lounge-sofa",
      "office-chair",
      "office-chair-teal",
      "plant",
      "plant-large",
      "plant-small",
      "reception-desk",
      "rug",
      "rug-round",
      "side-table",
      "sofa-pink",
      "sofa-teal",
      "sofa-yellow",
      "stool",
      "water-cooler",
      "water-cooler-modern",
      "whiteboard"
    ]
  },
  {
    "dir": "office",
    "label": "ออฟฟิศ",
    "keys": [
      "office/bin-1",
      "office/bin-2",
      "office/bin-3",
      "office/cabinet",
      "office/coffee-cup",
      "office/coffee-maker",
      "office/copier",
      "office/credenza",
      "office/cs-books",
      "office/cs-chair-1",
      "office/cs-chair-2",
      "office/cs-chair-3",
      "office/cs-chair-4",
      "office/cs-computer",
      "office/cs-counter",
      "office/cs-desk",
      "office/cs-desk-wide",
      "office/cs-monitor",
      "office/cs-stool-1",
      "office/cs-stool-2",
      "office/desk",
      "office/laptop-1",
      "office/laptop-2",
      "office/laptop-3",
      "office/laptop-4",
      "office/mailboxes",
      "office/phone",
      "office/portrait-1",
      "office/portrait-2",
      "office/table-dark",
      "office/table-grey",
      "office/table-tan",
      "office/tv",
      "office/tv-on",
      "office/water-cooler"
    ]
  },
  {
    "dir": "decor",
    "label": "ของแขวนผนัง",
    "keys": [
      "arched-window",
      "art-landscape",
      "art-poster",
      "corkboard",
      "glass-panel",
      "glass-wide",
      "neon-sign",
      "wall-clock",
      "wall-shelf",
      "window"
    ]
  },
  {
    "dir": "outdoor",
    "label": "กลางแจ้ง",
    "keys": [
      "bench",
      "bench-sofa",
      "bush-blob",
      "clover",
      "flower-mixed",
      "flower-pink",
      "flower-yellow",
      "fountain",
      "lamp-post",
      "pine",
      "planter-box",
      "planter-round",
      "rocks",
      "shrub",
      "sign-dir",
      "sign-team",
      "sign-welcome",
      "tree",
      "tree-oval"
    ]
  }
];

/** every key in one flat list, for lookups */
export const ALL_PROPS: string[] = CATALOGUE.flatMap((g) => g.keys);
